DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS person;

CREATE TABLE book
(
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title               VARCHAR NOT NULL,
    author              VARCHAR NOT NULL,
    year_of_publication INT CHECK (year_of_publication > 1000)
);

CREATE TABLE person
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR NOT NULL UNIQUE,
    year_of_birth INT CHECK (year_of_birth > 1900)
);
